# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release
sudo: required
cache:
  packages: true

os:
  - linux

jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test

r_binary_packages:
  - r-cran-data.table
  - r-cran-cluster
  - r-cran-caret
  - testthat

r_github_packages:
  - bimberlabinternal/OOSAP