# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release
cache:
  packages: true

os:
  - linux

jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test

r_github_packages:
  - bimberlabinternal/OOSAP