# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release
cache:
  packages: true

os:
  - linux

jobs:
  include:
    # Install some dependencies to speed build
    - stage: prepare cache
      script: Rscript -e 'remotes::install_github(\'cole-trapnell-lab/garnett\')'
    - stage: test
      script: true

# In theory this is faster than cran
addons:
  apt:
    packages:
      - r-cran-data.table
      - r-cran-cluster
      - r-cran-caret
      - testthat