# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release
cache:
  - packages
  - ccache

os:
  - linux

# see: https://pjs-web.de/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/
before_install:
  - chmod +x ./travis-config.sh && ./travis-config.sh

jobs:
  include:
    # Install some dependencies to speed build
    - stage: prepare cache
      script: true
    - stage: test
      script: true

addons:
  apt:
    packages:
      - ccache