# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release
sudo: required
cache:
  packages: true

os:
  - linux

r_binary_packages:
  - r-cran-data.table
  - r-cran-cluster
  - r-cran-caret
  - testthat

r_packages:
  - knitr
  - rmarkdown
  - remotes
  - utils