# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-release
cache:
  - packages
  - ccache

os:
  - linux

# see: https://pjs-web.de/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/
before_install:
  - chmod +x ./travis-config.sh && ./travis-config.sh

# see: https://docs.travis-ci.com/user/build-stages/warm-cache/
# https://travis-ci.community/t/is-there-a-way-not-to-install-r-packages-suggested-by-dependencies/3870/3
#jobs:
#  include:
#    # Install some dependencies to speed build
#    - stage: prepare cache
#      script: true
#    - stage: test

addons:
  apt:
    packages:
      - ccache
      - r-cran-data.table