# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
bioc_required: yes
use_bioc: yes

os:
  - linux
  - osx

r: bioc-release

packages:
  BiocManager

bioc_packages:
  DropletUtils