# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# and: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb

dist: bionic
language: r
r: release

# See: https://travis-ci.community/t/in-r-version-4-0-0-library-path-not-writable/9744/9
bioc_required: false

cache:
  - packages
  - pip
  - ccache

python:
  - "3.6"

os:
  - linux

# see: https://pjs-web.de/post/using-ccache-to-speed-up-r-package-checks-on-travis-ci/
before_install:
  - chmod +x ./travis-config.sh && ./travis-config.sh && python3 -m pip install --user wheel setuptools && python3 -m pip install --user umap-learn colorama >= 0.3.9

# https://jef.works/blog/2019/02/17/automate-testing-of-your-R-package/
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings


# see: https://docs.travis-ci.com/user/build-stages/warm-cache/
# https://travis-ci.community/t/is-there-a-way-not-to-install-r-packages-suggested-by-dependencies/3870/3
jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test
      script:
        - R CMD build --no-build-vignettes --no-manual .
        # See: https://github.com/r-lib/testthat/issues/515
        - # consider adding --as-cran
        - R CMD check --no-tests *tar.gz
        - Rscript -e 'res=devtools::test(reporter="summary");df=as.data.frame(res);if(sum(df$failed) > 0 || any(df$error)) {q(status=1)}'
      after_script:
        - Rscript -e 'BiocManager::valid()'
        - if [ -e ${TRAVIS_BUILD_DIR}/OOSAP.Rcheck/00install.out ];then cat ${TRAVIS_BUILD_DIR}/OOSAP.Rcheck/00install.out; else echo '00install.log not found'; fi

addons:
  apt:
    packages:
      - ccache
      - libgit2-dev
      - python3-pip
      - libfribidi-dev
      - libharfbuzz-dev

deploy:
  - provider: releases
    token: ${GH_TOKEN}
    file_glob: true
    file:
      - OOSAP_**.tar.gz
    cleanup: false
    on:
      tags: true